using System;

namespace TransparentClock
{
    /// <summary>
    /// Response model for successful QuickLink URL shortening requests.
    /// Contains the shortened URL, metadata, and remaining API credits.
    /// </summary>
    public class QuickLinkSuccessResponse
    {
        /// <summary>
        /// The shortened URL that users will visit.
        /// Example: "https://quicklink.short/abc123"
        /// </summary>
        public string ShortenedUrl { get; set; } = string.Empty;

        /// <summary>
        /// Direct redirect URL for accessing the shortened link.
        /// Used internally to construct the full redirect path.
        /// Example: "https://quicklink.io/redirect/abc123"
        /// </summary>
        public string DirectRedirectUrl { get; set; } = string.Empty;

        /// <summary>
        /// The original long URL that was shortened.
        /// Stored for reference and verification.
        /// </summary>
        public string LongUrl { get; set; } = string.Empty;

        /// <summary>
        /// The custom alias or code used in the shortened URL.
        /// Example: "abc123" from https://quicklink.short/abc123
        /// Can be user-provided or auto-generated by the API.
        /// </summary>
        public string Alias { get; set; } = string.Empty;

        /// <summary>
        /// Number of API credits remaining for this account.
        /// Decremented with each shortening request.
        /// Useful for warning users when credits run low.
        /// </summary>
        public int RemainingCredits { get; set; }

        /// <summary>
        /// When this shortened URL expires and becomes invalid.
        /// After this date, the link will no longer redirect.
        /// Null if the link does not expire.
        /// </summary>
        public DateTime? ExpiresAt { get; set; }
    }

    /// <summary>
    /// Response model for failed QuickLink URL shortening requests.
    /// Contains error status and user-friendly error message.
    /// </summary>
    public class QuickLinkErrorResponse
    {
        /// <summary>
        /// Error status code or category.
        /// Examples: "INVALID_URL", "RATE_LIMIT_EXCEEDED", "INVALID_CREDITS", "INVALID_ALIAS"
        /// Useful for programmatic error handling.
        /// </summary>
        public string Status { get; set; } = string.Empty;

        /// <summary>
        /// Human-readable error message describing what went wrong.
        /// Examples: "The provided URL is not valid", "You have exceeded your daily limit"
        /// Suitable for displaying to end users.
        /// </summary>
        public string Message { get; set; } = string.Empty;
    }
}
